# Generated by Django 5.2.17 on 2026-10-06 07:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BorrowHub BD', max_length=80)),
                ('tagline', models.CharField(default='Kenar dorkar nei — proyojon hole rent nao.', max_length=160)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Charged to the owner on the rental amount of every completed booking. Each booking stores the rate that applied when it was requested.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Commission (%)')),
                ('payment_window_hours', models.PositiveSmallIntegerField(default=24, help_text='Renter must pay within this many hours after the owner accepts.')),
                ('inspection_window_hours', models.PositiveSmallIntegerField(default=48, help_text='Renter has this long to accept or dispute a deposit deduction.')),
                ('require_listing_approval', models.BooleanField(default=False, help_text="If on, new listings stay 'Pending' until staff approve them.")),
                ('auto_verify_payments', models.BooleanField(default=True, help_text='DEMO MODE: payments are marked verified instantly. Turn OFF in production so staff verify each bKash/Nagad transaction ID manually (or connect a gateway).')),
                ('bkash_number', models.CharField(blank=True, default='01700-000000', max_length=20)),
                ('nagad_number', models.CharField(blank=True, default='01800-000000', max_length=20)),
                ('rocket_number', models.CharField(blank=True, default='01900-000000', max_length=20)),
                ('support_phone', models.CharField(blank=True, default='+880 1700-000000', max_length=30)),
                ('support_email', models.EmailField(blank=True, default='support@borrowhub.bd', max_length=254)),
                ('office_address', models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
