# Generated by Django 5.2.17 on 2026-10-06 07:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-box-seam', help_text='Bootstrap Icons class, e.g. bi-camera', max_length=40)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='brand / model')),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('new', 'Brand new'), ('like_new', 'Like new'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=10)),
                ('rules', models.TextField(blank=True, help_text='e.g. No outdoor use in rain. Return fully charged.', verbose_name='usage rules')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(1)], verbose_name='price per day (৳)')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='security deposit (৳)')),
                ('min_days', models.PositiveSmallIntegerField(default=1, verbose_name='minimum rental days')),
                ('max_days', models.PositiveSmallIntegerField(default=14, verbose_name='maximum rental days')),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur'), ('Narayanganj', 'Narayanganj'), ('Chattogram', 'Chattogram'), ('Cumilla', 'Cumilla'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Bogura', 'Bogura'), ("Cox's Bazar", "Cox's Bazar"), ('Jashore', 'Jashore'), ('Other', 'Other')], max_length=60)),
                ('area', models.CharField(max_length=100, verbose_name='area / thana')),
                ('pickup_available', models.BooleanField(default=True)),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='delivery fee (৳)')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('paused', 'Paused'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'city'], name='listings_li_status_deb39d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'listing')},
        ),
    ]
