# Generated by Django 5.2.17 on 2026-10-06 07:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^(?:\\+?88)?01[3-9]\\d{8}$', 'Enter a valid Bangladeshi mobile number, e.g. 01712345678.')])),
                ('city', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Gazipur', 'Gazipur'), ('Narayanganj', 'Narayanganj'), ('Chattogram', 'Chattogram'), ('Cumilla', 'Cumilla'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Bogura', 'Bogura'), ("Cox's Bazar", "Cox's Bazar"), ('Jashore', 'Jashore'), ('Other', 'Other')], max_length=60)),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='area / thana')),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('nid_number', models.CharField(blank=True, max_length=20, verbose_name='NID number')),
                ('nid_photo', models.ImageField(blank=True, upload_to='nid/', verbose_name='NID photo')),
                ('verification_status', models.CharField(choices=[('unverified', 'Not verified'), ('pending', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=12)),
                ('payout_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank account')], default='bkash', max_length=10)),
                ('payout_account', models.CharField(blank=True, help_text='Where BorrowHub sends your earnings and refunds.', max_length=60, verbose_name='payout account / number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
