# Generated by Django 5.2.17 on 2026-10-08 05:05

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid_photo',
            field=models.ImageField(blank=True, storage=core.storage.private_storage, upload_to='nid/', verbose_name='NID photo'),
        ),
    ]
