# Generated by Django 5.2.17 on 2026-10-06 07:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=12, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveSmallIntegerField(default=1)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Pickup from owner'), ('delivery', 'Delivery & return by owner')], default='pickup', max_length=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('message', models.TextField(blank=True, verbose_name='message to owner')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, help_text='Rental + delivery + refundable deposit', max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('owner_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rental + delivery − commission (before any deposit deduction)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Awaiting owner'), ('accepted', 'Awaiting payment'), ('paid', 'Paid · ready for handover'), ('active', 'On rent'), ('returned', 'Returned · inspection'), ('completed', 'Completed'), ('disputed', 'In dispute'), ('rejected', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('deposit_status', models.CharField(choices=[('unpaid', 'Not collected'), ('held', 'Held by BorrowHub'), ('refunded', 'Fully refunded'), ('partial', 'Partially refunded'), ('forfeited', 'Kept for damages')], default='unpaid', max_length=10)),
                ('deposit_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('inspection_note', models.TextField(blank=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='listings.listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_bookings', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('damage', 'Item damaged'), ('not_returned', 'Item not returned'), ('not_as_described', 'Item not as described'), ('deduction', 'Disagree with deposit deduction'), ('no_show', "Other party didn't show up"), ('other', 'Other')], max_length=20)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('review', 'Under review'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('final_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Set the amount of deposit that goes to the owner, then set status to Resolved.', max_digits=10, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bookings.booking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('collection', 'Renter → BorrowHub'), ('payout', 'BorrowHub → Owner'), ('refund', 'BorrowHub → Renter')], max_length=12)),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank transfer')], default='bkash', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trx_id', models.CharField(blank=True, max_length=40, verbose_name='transaction ID')),
                ('account', models.CharField(blank=True, max_length=60, verbose_name='sender / receiver number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed / rejected')], db_index=True, default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('for_owner', 'Renter reviewed owner/item'), ('for_renter', 'Owner reviewed renter')], max_length=12)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'status', 'start_date', 'end_date'], name='bookings_bo_listing_0c9bb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='booking_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('booking', 'reviewer')},
        ),
    ]
